blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/users/549577369342574602
  - name: Issues
    url: https://github.com/FJrodafo/npm-free-port/issues/new/choose
