blank_issues_enabled: false
contact_links:
  - name: Security advisories
    url: https://github.com/FJrodafo/npm-free-port/security/advisories
    about: Please report security vulnerabilities here.
