name: Benchmarks

on: [push, pull_request]

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: cd ./Testing && npm install
      - name: Loading time benchmark
        run: cd ./Testing && node ./benchmarks/loading.js
      - name: Package size benchmark
        run: cd ./Testing && node ./benchmarks/size.js
