name: Pipeline Deployment

on: [push, pull_request]

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: cd ./Test && npm install
      - name: Lint
        run: cd ./Test && node index.js
